import React, { useEffect } from "react"
import echarts from "echarts"
// import jsonData from "echarts/map/json/province/beijing.json"
import "echarts/map/js/province/beijing"

const data = [
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 273,
      suspect: 0,
      heal: 43,
      dead: 0,
      severe: 0,
      newConfirm: 230,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "丰台",
    id: "110106",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 175,
      suspect: 0,
      heal: 174,
      dead: 0,
      severe: 0,
      newHeal: 0,
    },
    extData: {},
    name: "境外输入",
    id: "C202006210854051",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 104,
      suspect: 0,
      heal: 39,
      dead: 0,
      severe: 0,
      newConfirm: 65,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "大兴",
    id: "110115",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 82,
      suspect: 0,
      heal: 64,
      dead: 0,
      severe: 0,
      newConfirm: 18,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "海淀",
    id: "110108",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 77,
      suspect: 0,
      heal: 75,
      dead: 0,
      severe: 0,
      newConfirm: 2,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "朝阳",
    id: "110105",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 59,
      suspect: 0,
      heal: 53,
      dead: 0,
      severe: 0,
      newConfirm: 6,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "西城",
    id: "110102",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 1,
      suspect: 0,
      heal: 0,
      dead: 0,
      severe: 0,
      storeConfirm: 1,
    },
    total: {
      confirm: 32,
      suspect: 0,
      heal: 29,
      dead: 0,
      severe: 0,
      newConfirm: 3,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "昌平",
    id: "110114",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 25,
      suspect: 0,
      heal: 25,
      dead: 0,
      severe: 0,
      newConfirm: 0,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "外地来京",
    id: "110100",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 20,
      suspect: 0,
      heal: 10,
      dead: 9,
      severe: 0,
      newConfirm: 1,
      newDead: 9,
      newHeal: 0,
    },
    extData: {},
    name: "通州",
    id: "110112",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 20,
      suspect: 0,
      heal: 16,
      dead: 0,
      severe: 0,
      newConfirm: 4,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "房山",
    id: "110111",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 19,
      suspect: 0,
      heal: 14,
      dead: 0,
      severe: 0,
      newConfirm: 5,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "东城",
    id: "110101",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 15,
      suspect: 0,
      heal: 14,
      dead: 0,
      severe: 0,
      newConfirm: 1,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "石景山",
    id: "110107",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 10,
      suspect: 0,
      heal: 10,
      dead: 0,
      severe: 0,
      newConfirm: 0,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "顺义",
    id: "110113",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 7,
      suspect: 0,
      heal: 7,
      dead: 0,
      severe: 0,
      newConfirm: 0,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "怀柔",
    id: "110116",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 7,
      suspect: 0,
      heal: 7,
      dead: 0,
      severe: 0,
      newConfirm: 0,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "密云",
    id: "110228",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 5,
      suspect: 0,
      heal: 3,
      dead: 0,
      severe: 0,
      newConfirm: 2,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "门头沟",
    id: "110109",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: 0,
      heal: 1,
      dead: 0,
      severe: 0,
      storeConfirm: -1,
    },
    total: {
      confirm: 1,
      suspect: 0,
      heal: 312,
      dead: 0,
      severe: 0,
      newConfirm: 0,
      newDead: -9,
      newHeal: 311,
    },
    extData: {},
    name: "未明确地区",
    id: "921100",
    lastUpdateTime: "2020-07-29 13:02:04",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 1,
      suspect: 0,
      heal: 1,
      dead: 0,
      severe: 0,
      newConfirm: 0,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "延庆",
    id: "110229",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 0,
      suspect: 0,
      heal: 0,
      dead: 0,
      severe: 0,
      newConfirm: 0,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "平谷",
    id: "110117",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
  {
    today: {
      confirm: 0,
      suspect: null,
      heal: 0,
      dead: 0,
      severe: null,
      storeConfirm: 0,
    },
    total: {
      confirm: 0,
      suspect: 0,
      heal: 0,
      dead: 0,
      severe: 0,
      newConfirm: -174,
      newDead: 0,
      newHeal: 0,
    },
    extData: {},
    name: "境外输入人员",
    id: "953563",
    lastUpdateTime: "2020-07-29 13:00:46",
    children: [],
  },
].map(item => ({
  [`${item.name}`]: item.total.confirm,
}))

const MapHK = () => {
  useEffect(() => {
    // echarts.registerMap("HK", jsonData)
    const map = echarts.init(document.getElementById("map"), "dark")
    map.setOption({
      title: {
        text: "香港18区人口密度 （2011）",
        subtext: "人口密度数据来自Wikipedia",
        sublink:
          "http://zh.wikipedia.org/wiki/%E9%A6%99%E6%B8%AF%E8%A1%8C%E6%94%BF%E5%8D%80%E5%8A%83#cite_note-12",
      },
      tooltip: {
        trigger: "item",
        formatter: "{b}<br/>{c} (p / km2)",
      },
      toolbox: {
        show: true,
        orient: "vertical",
        left: "right",
        top: "center",
        feature: {
          // dataView: { readOnly: false },
          // restore: {},
          // saveAsImage: {},
        },
      },
      visualMap: {
        min: 800,
        max: 50000,
        text: ["High", "Low"],
        realtime: false,
        calculable: true,
        inRange: {
          color: ["lightskyblue", "yellow", "orangered"],
        },
      },
      series: [
        {
          name: "香港18区人口密度",
          type: "map",
          mapType: "HK", // 自定义扩展图表类型
          data,
        },
      ],
    })
  })

  return (
    <div
      id="map"
      style={{
        width: "500px",
        height: "500px",
      }}
    ></div>
  )
}

export default MapHK
